//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoSM.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTAURANTE
    {
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int CodRest { get; set; }
        public Nullable<decimal> Contacto { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Parking { get; set; }
        public string Internet { get; set; }
        public Nullable<decimal> Visa { get; set; }
        public Nullable<decimal> Masterdcard { get; set; }
        public Nullable<int> Valoracion { get; set; }
        public Nullable<int> CodTipo { get; set; }
        public Nullable<int> CodDescuento { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        public Nullable<decimal> Celular { get; set; }
        public byte[] Horario { get; set; }
    }
}
