//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoSM.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
    }
}
